/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class za_co_technodev_javajni_Store */

#ifndef _Included_za_co_technodev_javajni_Store
#define _Included_za_co_technodev_javajni_Store
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    initializeStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_za_co_technodev_javajni_Store_initializeStore
  (JNIEnv *, jobject);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    finalizeStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_za_co_technodev_javajni_Store_finalizeStore
  (JNIEnv *, jobject);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    getInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_za_co_technodev_javajni_Store_getInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    setInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_za_co_technodev_javajni_Store_setInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_za_co_technodev_javajni_Store_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_za_co_technodev_javajni_Store_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    getColor
 * Signature: (Ljava/lang/String;)Lza/co/technodev/javajni/Color;
 */
JNIEXPORT jobject JNICALL Java_za_co_technodev_javajni_Store_getColor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    setColor
 * Signature: (Ljava/lang/String;Lza/co/technodev/javajni/Color;)V
 */
JNIEXPORT void JNICALL Java_za_co_technodev_javajni_Store_setColor
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    getIntegerArray
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_za_co_technodev_javajni_Store_getIntegerArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    setIntegerArray
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_za_co_technodev_javajni_Store_setIntegerArray
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    getColorArray
 * Signature: (Ljava/lang/String;)[Lza/co/technodev/javajni/Color;
 */
JNIEXPORT jobjectArray JNICALL Java_za_co_technodev_javajni_Store_getColorArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     za_co_technodev_javajni_Store
 * Method:    setColorArray
 * Signature: (Ljava/lang/String;[Lza/co/technodev/javajni/Color;)V
 */
JNIEXPORT void JNICALL Java_za_co_technodev_javajni_Store_setColorArray
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
